modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
credits="vincentmet" #optional
[[mods]] #mandatory
modId="yamma" #mandatory
version="1.14.4-0.2" #mandatory
displayName="YAMMA" #mandatory
description='''
ORESSSS!!!
'''